import { TypeSlideFilmes } from "../utils/TypeSlideFilmes";

export const slideFilmesMock: TypeSlideFilmes[] = [
  {
    'id': 1,
    'title': 'Avatar: Caminha das Águas',
    'descricao': "Após formar uma família, Jake Sully e Ney'tiri fazem de tudo para ficarem juntos. No entanto, eles devem sair de casa e explorar as regiões de Pandora quando uma antiga ameaça ressurge, e Jake deve travar uma guerra difícil contra os humanos.",
    'genero': 'filme',
    'categoria': ['acao'],
    'idioma': ['ingles', 'portugues'],
    'tamanho': '2GB',
    'createdAt': '2023-01-23',
    'updatedAt': '2023-01-24',
    'anoLancamento': 2022,
    'tempoFilme': 98,
    'imgURL': 'https://pbs.twimg.com/media/FSUlqUUXMAE_Gtl?format=jpg&name=medium',
    'trailer': 'https://www.youtube.com/watch?v=x5pZI-DmtrE',
  },
  {
    'id': 2,
    'title': 'Adão Negro',
    'descricao': 'Adão Negro é o filme solo do anti-herói, baseado no personagem em quadrinhos Black Adam (Dwayne Johnson) da DC Comics, grande antagonista de Shazam!, tendo no longa, sua história de origem explorada, e revelando seu passado de escravo no país Kahndaq. Nascido no Egito Antigo, o anti-herói tem super força, velocidade, resistência, capacidade de voar e de disparar raios. Alter ego de Teth-Adam e filho do faraó Ramsés II, Adão Negro foi consumido por poderes mágicos e transformado em um feiticeiro. Grande inimigo de Shazam! nas HQs, apesar dele acreditar em seu pontecial e, inclusive, oferecê-lo como um guerreiro do bem, Adão Negro acaba usando suas habilidades especiais para o mal. O anti-herói em busca de redenção ou um herói que se tornou vilão, pode ser capaz de destruir tudo o que estiver pela frente - ou de encontrar seu caminho.',
    'genero': 'filme',
    'categoria': ['acao'],
    'idioma': ['ingles', 'portugues'],
    'tamanho': '2GB',
    'createdAt': '2023-01-23',
    'updatedAt': '2023-01-24',
    'anoLancamento': 2022,
    'tempoFilme': 98,
    'imgURL': 'https://static3.tcdn.com.br/img/img_prod/352023/90_camiseta_unissex_adao_negro_force_card_adao_negro_9981_3_df26c3a95c3562177f153f146ab2e0b7.jpg',
    'trailer': 'https://www.youtube.com/watch?v=JJFAeByX-PE',
  },
  {
    'id': 3,
    'title': 'Pantera Negra: Wakanda Forever',
    'descricao': "Rainha Ramonda, Shuri, M'Baku, Okoye e Dora Milaje, lutam para proteger sua nação das potências mundiais intervenientes após a morte do rei T'Challa. Enquanto os wakandanos se esforçam para abraçar seu próximo capítulo, os heróis devem se unir com a ajuda de War Dog Nakia e Everett Ross e forjar um novo caminho para o reino de Wakanda.",
    'genero': 'filme',
    'categoria': ['acao'],
    'idioma': ['ingles', 'portugues'],
    'tamanho': '2GB',
    'createdAt': '2023-01-23',
    'updatedAt': '2023-01-24',
    'anoLancamento': 2022,
    'tempoFilme': 98,
    'imgURL': 'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgxOrfwvlqheorb4VwS0tzV5XMTb9aNH838YlNjhuyt03jraFw1EiRdIe7s0xIddaoZdO9atsiFm8ksOipiah37BEpoXX7MukHmwJxcr6aDIOaOBZPtEquwKuQH5Ln_gjAcmjnKwYjT9cH5nnRjTCRyorSgzQRcDqdXsbZCBd80XtB2PqAhVCY/s1600/EFE2E307-83AE-456BA5FB-79C49354AA88.jpeg',
    'trailer': 'https://www.youtube.com/watch?v=FR9iLjOubWc',
  },
  {
    'id': 4,
    'title': 'Avatar: Caminha das Águas',
    'descricao': "Após formar uma família, Jake Sully e Ney'tiri fazem de tudo para ficarem juntos. No entanto, eles devem sair de casa e explorar as regiões de Pandora quando uma antiga ameaça ressurge, e Jake deve travar uma guerra difícil contra os humanos.",
    'genero': 'filme',
    'categoria': ['acao'],
    'idioma': ['ingles', 'portugues'],
    'tamanho': '2GB',
    'createdAt': '2023-01-23',
    'updatedAt': '2023-01-24',
    'anoLancamento': 2022,
    'tempoFilme': 98,
    'imgURL': 'https://pbs.twimg.com/media/FSUlqUUXMAE_Gtl?format=jpg&name=medium',
    'trailer': 'https://www.youtube.com/watch?v=x5pZI-DmtrE',
  },
  {
    'id': 5,
    'title': 'Adão Negro',
    'descricao': 'Adão Negro é o filme solo do anti-herói, baseado no personagem em quadrinhos Black Adam (Dwayne Johnson) da DC Comics, grande antagonista de Shazam!, tendo no longa, sua história de origem explorada, e revelando seu passado de escravo no país Kahndaq. Nascido no Egito Antigo, o anti-herói tem super força, velocidade, resistência, capacidade de voar e de disparar raios. Alter ego de Teth-Adam e filho do faraó Ramsés II, Adão Negro foi consumido por poderes mágicos e transformado em um feiticeiro. Grande inimigo de Shazam! nas HQs, apesar dele acreditar em seu pontecial e, inclusive, oferecê-lo como um guerreiro do bem, Adão Negro acaba usando suas habilidades especiais para o mal. O anti-herói em busca de redenção ou um herói que se tornou vilão, pode ser capaz de destruir tudo o que estiver pela frente - ou de encontrar seu caminho.',
    'genero': 'filme',
    'categoria': ['acao'],
    'idioma': ['ingles', 'portugues'],
    'tamanho': '2GB',
    'createdAt': '2023-01-23',
    'updatedAt': '2023-01-24',
    'anoLancamento': 2022,
    'tempoFilme': 98,
    'imgURL': 'https://static3.tcdn.com.br/img/img_prod/352023/90_camiseta_unissex_adao_negro_force_card_adao_negro_9981_3_df26c3a95c3562177f153f146ab2e0b7.jpg',
    'trailer': 'https://www.youtube.com/watch?v=JJFAeByX-PE',
  },
  {
    'id': 6,
    'title': 'Pantera Negra: Wakanda Forever',
    'descricao': "Rainha Ramonda, Shuri, M'Baku, Okoye e Dora Milaje, lutam para proteger sua nação das potências mundiais intervenientes após a morte do rei T'Challa. Enquanto os wakandanos se esforçam para abraçar seu próximo capítulo, os heróis devem se unir com a ajuda de War Dog Nakia e Everett Ross e forjar um novo caminho para o reino de Wakanda.",
    'genero': 'filme',
    'categoria': ['acao'],
    'idioma': ['ingles', 'portugues'],
    'tamanho': '2GB',
    'createdAt': '2023-01-23',
    'updatedAt': '2023-01-24',
    'anoLancamento': 2022,
    'tempoFilme': 98,
    'imgURL': 'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgxOrfwvlqheorb4VwS0tzV5XMTb9aNH838YlNjhuyt03jraFw1EiRdIe7s0xIddaoZdO9atsiFm8ksOipiah37BEpoXX7MukHmwJxcr6aDIOaOBZPtEquwKuQH5Ln_gjAcmjnKwYjT9cH5nnRjTCRyorSgzQRcDqdXsbZCBd80XtB2PqAhVCY/s1600/EFE2E307-83AE-456BA5FB-79C49354AA88.jpeg',
    'trailer': 'https://www.youtube.com/watch?v=FR9iLjOubWc',
  },
  {
    'id': 7,
    'title': 'Avatar: Caminha das Águas',
    'descricao': "Após formar uma família, Jake Sully e Ney'tiri fazem de tudo para ficarem juntos. No entanto, eles devem sair de casa e explorar as regiões de Pandora quando uma antiga ameaça ressurge, e Jake deve travar uma guerra difícil contra os humanos.",
    'genero': 'filme',
    'categoria': ['acao'],
    'idioma': ['ingles', 'portugues'],
    'tamanho': '2GB',
    'createdAt': '2023-01-23',
    'updatedAt': '2023-01-24',
    'anoLancamento': 2022,
    'tempoFilme': 98,
    'imgURL': 'https://pbs.twimg.com/media/FSUlqUUXMAE_Gtl?format=jpg&name=medium',
    'trailer': 'https://www.youtube.com/watch?v=x5pZI-DmtrE',
  },
  {
    'id': 8,
    'title': 'Adão Negro',
    'descricao': 'Adão Negro é o filme solo do anti-herói, baseado no personagem em quadrinhos Black Adam (Dwayne Johnson) da DC Comics, grande antagonista de Shazam!, tendo no longa, sua história de origem explorada, e revelando seu passado de escravo no país Kahndaq. Nascido no Egito Antigo, o anti-herói tem super força, velocidade, resistência, capacidade de voar e de disparar raios. Alter ego de Teth-Adam e filho do faraó Ramsés II, Adão Negro foi consumido por poderes mágicos e transformado em um feiticeiro. Grande inimigo de Shazam! nas HQs, apesar dele acreditar em seu pontecial e, inclusive, oferecê-lo como um guerreiro do bem, Adão Negro acaba usando suas habilidades especiais para o mal. O anti-herói em busca de redenção ou um herói que se tornou vilão, pode ser capaz de destruir tudo o que estiver pela frente - ou de encontrar seu caminho.',
    'genero': 'filme',
    'categoria': ['acao'],
    'idioma': ['ingles', 'portugues'],
    'tamanho': '2GB',
    'createdAt': '2023-01-23',
    'updatedAt': '2023-01-24',
    'anoLancamento': 2022,
    'tempoFilme': 98,
    'imgURL': 'https://static3.tcdn.com.br/img/img_prod/352023/90_camiseta_unissex_adao_negro_force_card_adao_negro_9981_3_df26c3a95c3562177f153f146ab2e0b7.jpg',
    'trailer': 'https://www.youtube.com/watch?v=JJFAeByX-PE',
  },
  {
    'id': 9,
    'title': 'Pantera Negra: Wakanda Forever',
    'descricao': "Rainha Ramonda, Shuri, M'Baku, Okoye e Dora Milaje, lutam para proteger sua nação das potências mundiais intervenientes após a morte do rei T'Challa. Enquanto os wakandanos se esforçam para abraçar seu próximo capítulo, os heróis devem se unir com a ajuda de War Dog Nakia e Everett Ross e forjar um novo caminho para o reino de Wakanda.",
    'genero': 'filme',
    'categoria': ['acao'],
    'idioma': ['ingles', 'portugues'],
    'tamanho': '2GB',
    'createdAt': '2023-01-23',
    'updatedAt': '2023-01-24',
    'anoLancamento': 2022,
    'tempoFilme': 98,
    'imgURL': 'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgxOrfwvlqheorb4VwS0tzV5XMTb9aNH838YlNjhuyt03jraFw1EiRdIe7s0xIddaoZdO9atsiFm8ksOipiah37BEpoXX7MukHmwJxcr6aDIOaOBZPtEquwKuQH5Ln_gjAcmjnKwYjT9cH5nnRjTCRyorSgzQRcDqdXsbZCBd80XtB2PqAhVCY/s1600/EFE2E307-83AE-456B-A5FB-79C49354AA88.jpeg',
    'trailer': 'https://www.youtube.com/watch?v=FR9iLjOubWc',
  }
]
